---
title: "o-Well-1"
author: "Kaleb Willis"
output: html_document
---

```{r}
which.github = "remote"

github.local = "X:/_git_/WSU_STAT419_2021/";
github.remote = "https://raw.githubusercontent.com/KalebWillis/WSU_STAT419_2021/main/";

if(which.github == "remote")
  {
   include.me = paste0(github.remote, "o-well/");
   library(devtools);
   #source(include.me);
}else
  {
   include.me = paste0(github.local, "o-well/");
   #source(include.me);
  
}
```
# Read in txt files
```{r}
path.data = paste0(include.me, "datasets/")
owell.metals = read.delim(paste0(path.data, "table1.txt"), header = TRUE, sep = "")
owell.chemistry = read.delim(paste0(path.data, "table2.txt"), header = TRUE, sep = "")
well.location = read.delim(paste0(path.data, "wells-location.txt"), header = TRUE, sep = "|")
well.faults = read.delim(paste0(path.data, "faults.txt"), header = TRUE, sep = "")
well.geology = read.delim(paste0(path.data, "geology.txt"), header = TRUE, sep = "")
```
# Append location, fault, and geology column
```{r}
owell.metals$latitude = well.location$latitude;
owell.metals$longitude = well.location$longitude;
owell.metals$altitude.ft = well.location$altitude.ft;
owell.metals$fault = well.faults$fault;
owell.metals$geology = well.geology$geology;
write.table(owell.metals, file = "owell-metals.txt", append = FALSE, sep = "|", row.names = TRUE, col.names = TRUE)

owell.chemistry$latitude = well.location$latitude;
owell.chemistry$longitude = well.location$longitude;
owell.chemistry$altitude.ft = well.location$altitude.ft;
owell.chemistry$fault = well.faults$fault;
owell.chemistry$geology = well.geology$geology;
write.table(owell.chemistry, file = "owell-chemistry.txt", append = FALSE, sep = "|", row.names = TRUE, col.names = TRUE)
```
# Create lists
```{r}
wells = list();
wells$saudi$metals = owell.metals;
wells$saudi$chemistry = owell.chemistry;

```
# Write out files
```{r}
myfile = paste0(include.me, "well.RDS");
saveRDS(wells, file = "well.rds");
myfile = paste0(include.me, "well.txt");
write.table(wells, file = "well.txt", append = FALSE, sep = "|", row.names = TRUE, col.names = TRUE)
```
