---
title: "R Notebook: intro"
author: "Kaleb Willis"
output: html_notebook
---
```{r}
which.github = "local"

github.local = "X:/_git_/WSU_STAT419_2021/r-intro/";
github.remote = "";

if(which.github == "remote")
  {
   include.me = paste0(github.remote, "");
   library(devtools);
   source(include.me);
}else
  {
   include.me = paste0(github.local, "");
   source(include.me);
  
}
```


# handShake
```{r}
library(plotrix)
library(pracma)
is.wholenumber = function(x, tol = .Machine$double.eps^0.5)
{
  abs(x - round(x)) < tol
}

handShake = function(n=1, plotMe =FALSE)
{
  if(n < 1) {stop("n cannot be less than 1");}
  if(!is.wholenumber(n)) {stop("not an integer");}
  h = n*(n-1)/2;
  if(plotMe) 
     {
     r = n
     plot(0,0,xlim=c(-n-1,n+1), ylim=c(-n-1,n+1), main=paste0(h," handshakes for ",n," people"), xlab="", ylab="", xaxt="n", yaxt="n",bty="n", asp=1);
     draw.circle(0,0,n,n+100);
     #draw.circle(0,0,n,n);
     #points(0,r, pch=16)
     #plot(r*sin(theta),r*cos(theta));
     #handshake.points = data.matrix(a = 1:n, b = )
     for(i in 1:n){
        deg = 360/n;
        theta = 2*pi*deg/360;
        plot(r*sin(i*theta),r*cos(i*theta), pch=16, )
        lines(r*sin(i*theta), r*cos(i*theta), type="l")
     }
  }
 h;
}
```
# Declaration of Independence

# Determinant of 3x3 matrix